### ISSUE TITLE
Compatible with Laravel Websockets and Flutter Laravel Echo?

### ISSUE THREAD

**Issue by nicolasvahidzein** [mcfugger/dart_pusher_channels#15]
Thank you for this package that was recommended to me but is it compatible with laravel echo and laravel websockets on my own server and using a pusher replacement service?

I don't have a key to put in the options.

If you please have a sample config to use for this setup i would be very grateful.

**Comment by nicolasvahidzein** [comment]
also should we use .ws or .wss to connect?

**Comment by mcfugger** [comment]
Hello, if you have the security context on your server use `wss`, otherwise - use `ws`.

**Comment by mcfugger** [comment]
> Thank you for this package that was recommended to me but is it compatible with laravel echo and laravel websockets on my own server and using a pusher replacement service?
> 
> I don't have a key to put in the options.
> 
> If you please have a sample config to use for this setup i would be very grateful.

@nicolasvahidzein I've read the issue and added a feature to add custom path to `PusherChannelOptions`. 

Also, I've updated API reference in version `0.2.8` just today (which is an inline code reference) on [pub.dev](https://pub.dev/packages/dart_pusher_channels).  [Link to API reference of `PusherChannelOptions`](https://pub.dev/documentation/dart_pusher_channels/latest/dart_pusher_channels_base/PusherChannelOptions-class.html).

So this may be your case:
```dart
// If your server is `wss`
const withPath = PusherChannelOptions.wss(
          host: 'example.com',
          path: '/CUSTOM_PATH',
          port: 443,
          key: null,
          protocol: 7);
// If your server is `ws`
const withPath = PusherChannelOptions.ws(
          host: 'example.com',
          path: '/CUSTOM_PATH',
          port: 12,
          key: null,
          protocol: 7);
```

Pay an attention to `/CUSTOM_PATH` - it's you endpoint to web socket connection (alternative to /app/[KEY]). If you do not have path set `path:'/'`

For the other samples, please check the [test file](https://github.com/mcfugger/dart_pusher_channels/blob/master/test/dart_pusher_channels_test.dart) (group with name "Pusher Channel options uri must be convinient").

I've described and tested most of the use-cases

**Comment by mcfugger** [comment]
@nicolasvahidzein By the way, my partner developer used own Laravel server as host. So, I think yes - if your laravel library supports Pusher protocol - it's okay. 

Specifically, in this client library I used `web_socket_channel` for `WebSocketChannelConnectionDelegate` under the hood.

**Comment by mcfugger** [comment]
@nicolasvahidzein 

Additionally, here is a link to [API reference](https://pub.dev/documentation/dart_pusher_channels/latest/dart_pusher_channels_base/PusherChannelOptions/PusherChannelOptions.html) of the default constructor of `PusherChannelOptions`. It now has detailed description of the parameters.

If these comments helped you - I will close the issue. Please, inform me about your progress.

**Comment by nicolasvahidzein** [comment]
Hello @mcfugger I upgraded to 0.3.0 and i'm getting a message saying that:

'PusherChannelOptions' is deprecated and shouldn't be used. The class was renamed to [PusherChannelsOptions]..
Try replacing the use of the deprecated member with the replacement.

I wrote it like this:
```
				PusherChannelOptions options = PusherChannelOptions(
					scheme: 'ws',
					key: null,
					host: websocketsDomain,
					path: websocketsAuthEndpointRelativeUrl,
					port: websocketsPort,
					protocol: 7,
					version: '7.0.3',
					cluster: websocketsCluster,
				);
```

**Comment by nicolasvahidzein** [comment]
Please disregard previous comment, i had missed the added "s" in the variable name.

Will test right now.

**Comment by mcfugger** [comment]
@nicolasvahidzein 
Look, you should read [API reference](https://pub.dev/documentation/dart_pusher_channels/latest/dart_pusher_channels_base/PusherChannelOptions/PusherChannelOptions.html). `path` is actually not the authentication endpoint, it is endpoint to your connection.
Typically, pusher channels urls look like this:
`[scheme]://[host]:[port]/app/[key]`
If you provide cluster:
`[scheme]://ws-[cluster_name].[host]:[port]/app/[key]`
But you said that you don't have `key`, so I added feature to set custom path, so if you provide `path`, your url will be like this:
`[scheme]://ws-[cluster_name].[host]:[port][path]`.
`Note:` There is no `/`(slash) by default in front of the path - you should add it.
How to know what url is generated by `PusherChannelsOptions`?
```dart
PusherChannelOptions options = PusherChannelOptions(
					scheme: 'ws',
					key: null,
					host: websocketsDomain,
					path: websocketsAuthEndpointRelativeUrl,
					port: websocketsPort,
					protocol: 7,
					version: '7.0.3',
					cluster: websocketsCluster,
				);
// Check it
print(options.uri);
```
Or take a look at [test file](https://github.com/mcfugger/dart_pusher_channels/blob/master/test/dart_pusher_channels_test.dart) (group with name "Pusher Channel options uri must be convinient"). There are a lot of samples compared with its expected values.
For example (from test file):
```dart
const withPath = PusherChannelsOptions(
          scheme: 'ws',
          host: 'example.com',
          path: '/CUSTOM_PATH',
          port: 12,
          key: null,
          protocol: 7);

      expect(
          withPath.uri,
          Uri.parse(
              'ws://example.com:12/CUSTOM_PATH?client=dart&version=$kDartPusherChannelsLibraryVersion&protocol=7'));
```

**Comment by mcfugger** [comment]
`path` is not an endpoint for authentication - it's alternative if you don't have `key`.

**Comment by mcfugger** [comment]
@nicolasvahidzein Please, inform me about your progress in this thread.

**Comment by mcfugger** [comment]
@nicolasvahidzein Please, inform me about your progress in this thread.

**Comment by nicolasvahidzein** [comment]
> `path` is not an endpoint for authentication - it's alternative if you don't have `key`.

i'm confused, so what do i put in path then? I'll paste here all my values and you can tell me what i should use.

**Comment by mcfugger** [comment]
@nicolasvahidzein Okay, replace your original host with example.com to keep it safe here. If you provide your full link, I will tell

**Comment by nicolasvahidzein** [comment]
const String websocketsAppIdDev = 'RTYG-4852-EFTG-1234';
const String websocketsDomainDev = '192.168.4.8';
const String websocketsAuthEndpointDomainDev = 'http://192.168.4.8:4521';
const String websocketsAuthEndpointRelativeUrlDev = '/broadcasting/auth';
const int websocketsPortDev = 3009;
const String websocketsClusterDev = 'mt1';
const bool websocketsEncryptedDev = false;

```

				PusherChannelsOptions options = PusherChannelsOptions(
					scheme: 'ws',
					key: null,
					host: websocketsDomainDev,
					path: websocketsAuthEndpointRelativeUrlDev,
					port: websocketsPortDev,
					protocol: 7,
					version: '7.0.3',
					cluster: websocketsClusterDev,
				);
				
				PusherChannelsClient pusher = PusherChannelsClient.websocket(
					reconnectTries: 3,
					options: options,
					onConnectionErrorHandle: (error, trace, refresh) {
						print('websocket error: $error');
					},
				);
				
				//TURNED INTO A CLASS VARIABLE
				//Channel? channel;
				
				//TURNED INTO A CLASS VARIABLE
				//StreamSubscription? eventSubscription;
				
				pusher.onConnectionEstablished.listen((_) async {
					
					//connect to a private channel
					channel ??= pusher.privateChannel(
						'user.${myUserId!}',
						// This is a default authorization delegate
						// to authorize to the channels
						// You may implement your own authorization delegate
						// implementing [AuthorizationDelegate] interface
						// Use 'http' or 'https' scheme
						TokenAuthorizationDelegate(
							authorizationEndpoint: Uri.parse(websocketsAuthEndpointDomain + websocketsAuthEndpointRelativeUrl),
							headers: {
								'Authorization':  'Bearer ' + accessToken,
								'Content-Type': 'application/json',
								'Accept': 'application/json'
							}
						)
					);
					
					await eventSubscription?.cancel();
					
					// Ensure you bind to the channel before subscribing, otherwise - you will miss some events
					eventSubscription = channel?.bind('UserStatusChange').listen((event) {
						//listen for events form the channel here
						
						print(event);
						
					});
					
					channel!.subscribe();
					
				});
				
				//connect the service
				pusher.connect();
				
```

**Comment by nicolasvahidzein** [comment]
And if i replace the values to make it easy to read:
```
PusherChannelsOptions options = PusherChannelsOptions(
	scheme: 'ws',
	key: null,
	host: '192.168.4.8',
	path: '/broadcasting/auth',
	port: 3009,
	protocol: 7,
	version: '7.0.3',
	cluster: 'mt1',
);
```

**Comment by mcfugger** [comment]
What is `RTYG-4852-EFTG-1234`?

**Comment by nicolasvahidzein** [comment]
App ID set in laravel websockets. Not sure if it's useful.

**Comment by mcfugger** [comment]
To make it clear, are you sure you using Pusher protocol?

**Comment by nicolasvahidzein** [comment]
Yes sir. This is how i was connecting using laravel echo and laravel pusher flutter packages:

```
PusherOptions options = PusherOptions(
					host: websocketsDomain,
					port: websocketsPort,
					cluster: websocketsCluster,
					encrypted: websocketsEncrypted,
					auth: PusherAuth(
						websocketsAuthEndpointDomain + websocketsAuthEndpointRelativeUrl,
						headers: {
							'Authorization':  'Bearer ' + accessToken,
							'Content-Type': 'application/json',
							'Accept': 'application/json'
						},
					),
				);
				
				LaravelFlutterPusher pusher = LaravelFlutterPusher(
					websocketsAppId,
					options,
					enableLogging: true,
				);
				
				_echo = Echo(
					broadcaster: EchoBroadcasterType.Pusher,
					client: pusher,
				);
				
				pusher.connect(onConnectionStateChange: (ConnectionStateChange event) {
					
					print('event:');
					print(event);
					print(event.currentState);
					
					if (event.currentState == 'CONNECTED') {
						
						_appStore!.setEcho(_echo);
						
						_appStore!.setWebsocketConnection(true);
						
						_appStore!.incrementWebsocketConnectionAttempt();
						
					} else if (event.currentState == 'DISCONNECTED') {
						
						_appStore!.setWebsocketConnection(false);
						
					}
					
				}).onError((error, stackTrace) {
					print('websocket error: $error');
				});
				
				//connect to the private channel
				//you can piggy back channel listeners if you are adding more
				_echo!.private('user.${myUserId!}').listen('UserStatusChange', (event) {
					
					print(event);
					
				});
```

**Comment by mcfugger** [comment]
Okay, try this (removed the cluster) (removed the version because it's set as default with the version of the library)
```dart
PusherChannelsOptions options = PusherChannelsOptions(
	scheme: 'ws',
	key: 'RTYG-4852-EFTG-1234',
	host: '192.168.4.8',
	port: 3009,
	protocol: 7,
);
```

**Comment by mcfugger** [comment]
Okay, try this (removed the cluster) (removed the version because it's set as default with the version of the library)

PusherChannelsOptions options = PusherChannelsOptions(
	scheme: 'ws',
	path: '',
	host: '192.168.4.8',
	port: 3009,
	protocol: 7,
);

**Comment by nicolasvahidzein** [comment]
ok doing it now.
This below looks right to you? The URI?

```
channel ??= pusher.privateChannel(
'user.${myUserId!}',
TokenAuthorizationDelegate(
	authorizationEndpoint: Uri.parse('http://192.168.4.8:4521/broadcasting/auth'),
	headers: {
		'Authorization':  'Bearer ' + accessToken,
		'Content-Type': 'application/json',
		'Accept': 'application/json'
	}
)
);
```

**Comment by mcfugger** [comment]
Okay, try this (removed the cluster) (removed the version because it's set as default with the version of the library)
```dart
PusherChannelsOptions options = PusherChannelsOptions(
	scheme: 'ws',
	path: '',
	host: '192.168.4.8',
	port: 3009,
	protocol: 7,
);
```

**Comment by mcfugger** [comment]
So this library was made accoring to the client [API documentation](https://pusher.com/docs/channels/library_auth_reference/pusher-websockets-protocol/).

Did you test your server in browser?
If yes, then what url you used to test your web socket server?
Typically, they look like this:
`ws://ws-ap1.pusher.com:80/app/APP_KEY?client=js&version=7.0.3&protocol=5`

What yours looks like?

**Comment by nicolasvahidzein** [comment]
websocket error: WebSocketChannelException: WebSocketChannelException: WebSocketException: Connection to 'http://192.168.2.5:3009?client=dart&version=0.2.9&protocol=7#' was not upgraded to websocket

**Comment by nicolasvahidzein** [comment]
laravel websockets you connect to the server directly and authentify using the domain and authentication relative path. 

there is no ws link involved.

**Comment by nicolasvahidzein** [comment]
laravel websockets you connect to the server directly and authentify using the domain and authentication relative path. 

there is no ws link involved.

**Comment by mcfugger** [comment]
I guess, I know what's the case. I think it's because of the query parameters. Let me fix it in 10 minutes. I will add option to omit them.

**Comment by nicolasvahidzein** [comment]
ok. But i'm curious, others are using your package as is with laravel websockets on a custom server so how are they doing it?
Your partner is achieving this how, do you know?

**Comment by nicolasvahidzein** [comment]
we also need to add the auth endpoints too i think.

**Comment by mcfugger** [comment]
> ok doing it now. This below looks right to you? The URI?
> 
> ```
> channel ??= pusher.privateChannel(
> 'user.${myUserId!}',
> TokenAuthorizationDelegate(
> 	authorizationEndpoint: Uri.parse('http://192.168.4.8:4521/broadcasting/auth'),
> 	headers: {
> 		'Authorization':  'Bearer ' + accessToken,
> 		'Content-Type': 'application/json',
> 		'Accept': 'application/json'
> 	}
> )
> );
> ```

Here is where you can provide auth endpoint. This feature was added in very first versions :)

**Comment by mcfugger** [comment]
> ok. But i'm curious, others are using your package as is with laravel websockets on a custom server so how are they doing it?
> Your partner is achieving this how, do you know?

See the closed issues of this library, the folks may help you with that, I will ask my teammate about it too

**Comment by mcfugger** [comment]
The `0.3.1` is live now.

If you add `shouldSupplyQueryMetaData: false`. It will omit query parameters. Try it please.
```dart
const noQuery = PusherChannelsOptions(
          scheme: 'ws',
          host: 'example.com',
          port: 12,
          key: null,
          path: '',
          shouldSupplyQueryMetaData: false,
          protocol: 7);
      expect(noQuery.uri, Uri.parse('ws://example.com:12'));
```

**Comment by mcfugger** [comment]
@nicolasvahidzein Test the new version with as described above, please.

**Comment by mcfugger** [comment]
> The `0.3.1` is live now.
> 
> If you add `shouldSupplyQueryMetaData: false`. It will omit query parameters. Try it please.
> 
> ```dart
> const noQuery = PusherChannelsOptions(
>          scheme: 'ws',
> 	 path: '',
>          key:null,
> 	 host: '192.168.4.8',
> 	  port: 3009,
> 	  protocol: 7,
>           shouldSupplyQueryMetaData: false);
> ```
@nicolasvahidzein Try this

**Comment by mcfugger** [comment]
@nicolasvahidzein I will be waiting for the updates in your progress. Keep the thread up-to-date, we will go through it.

**Comment by nicolasvahidzein** [comment]
ok testing now

**Comment by nicolasvahidzein** [comment]
WebSocketException: Connection to 'http://192.168.2.5:3009#' was not upgraded to websocket

**Comment by nicolasvahidzein** [comment]
it added a pound symbol but i think we are close.

**Comment by mcfugger** [comment]
@nicolasvahidzein No, pound symbol is part of an exception. You must now check if your host server was upgraded to web sockets or try different port. When I had this exception with my project on test server - I tried always port 12.

The issue on server side.

**Comment by nicolasvahidzein** [comment]
I am not seeing any connection attempt on the server, maybe i am looking in the wrong place. Is there another place besides my laravel websocket process i can check?

**Comment by mcfugger** [comment]
Try to upgrade your server to ws or wss. What of you use ngninx or Apache?

I am not a server-side developer. These answers might be helpful:
https://stackoverflow.com/a/72135334/12177707

I would recommend also those things:
1. Make sure your scheme. ws or wss
2. Check if your port is right. From my experience - I used to have similiar exception. My partner said to use port 3009, but it kept giving exceptions. Then I used port 12 (ws schemes usually use 12 port, wss 443)

**Comment by nicolasvahidzein** [comment]
i'm using port 3009 for sure. No doubt about that as it's working with laravel_flutter_pusher.

**Comment by mcfugger** [comment]
laravel_flutter_pusher based on native plugins, so my guess is that they allow connections over http/https schemes. This library tries to connect using ws/wss schemes ([web_socket_channel](https://pub.dev/packages/web_socket_channel)) and your server does not allow connection because the server was not upgraded to web sockets (ws/wss) as the exception claims.

**Comment by nicolasvahidzein** [comment]
yikes. This is a problem. I wonder how Yassine did it. I will wait for him to reply to my email and ask him and revert back here.

Thanks a lot @mcfugger i'll update you here. All your hard work and wonderful plugin are appreciated.

**Comment by mcfugger** [comment]
Thank you very much! I will keep the issue open unless assumption is confirmed.
It might be helpful:
https://stackoverflow.com/a/72135334/12177707

Will be waiting for updates here.

**Comment by nicolasvahidzein** [comment]
I should mention that i am using an older version of laravel websocket v1.1 on Laravel v 5.8. Not sure if that is the issue.

**Comment by mcfugger** [comment]
```
....
GET /chat HTTP/1.1
Host: server.example.com
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: SOME_KEY
....
Origin: http://example.com
```

@nicolasvahidzein Do you know where to finds these configs on a server?

I think the line makes sense:
```
Upgrade: websocket
```

**Comment by mcfugger** [comment]
And check this informative answer too:
https://stackoverflow.com/questions/66597039/laravel-websocket-wont-connect-on-production

**Comment by nicolasvahidzein** [comment]
also i think i am using pusher v5 since my version of laravel websockets is so old.

**Comment by nicolasvahidzein** [comment]
I spoke to one of your users Yassine who was very helpful. I guess i need to upgrade my packages (websockets and pusher) and then implement your package. No choice. My versions are too old.

**Comment by mcfugger** [comment]
@nicolasvahidzein It's a power of community :) Tell me when you make it with the new version of Laravel - then I will close the issue

**Comment by nicolasvahidzein** [comment]
Hey @mcfugger Kerim, updating was the key. All works great now!!! Thanks to you and Yassine we figured it out. Cheers and take good care of yourself.
